version: "3"
services:
  # port 8123
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./HA/config/:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  # port 6052
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./ESPHome/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host

  nest-server:
    build: ./NestJs
    image: nest
    restart: unless-stopped
    ports:
      - "3015:3000"

  svelte-server:
    build: ./Svelte
    image: svelte
    restart: unless-stopped
    ports:
      - "3010:80"

  ustreamer:
    build: ./UStreamer
    image: ustreamer
    restart: unless-stopped
    ports:
      - "8080:8080"
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
