version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./HA/config/:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./ESPHome/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host

  nest-server:
    build: ./NestJs
    image: nest
    restart: unless-stopped
    ports:
      - "3015:3000"

  svelte-server:
    build: ./Svelte
    image: svelte
    restart: unless-stopped
    ports:
      - "3010:80"

  # camera-server:
  #   build: ./Mjpg-streamer
  #   image: mjpg
  #   restart: unless-stopped
  #   devices:
  #     - "/dev/video0:/dev/video0"
  #     - "/dev/video1:/dev/video1"
  #   ports:
  #     - "8080:8080"

  ustreamer:
    build: ./UStreamer
    image: ustreamer
    ports:
      - "8080:8080"
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
