version: "3"
services:
  # port 8123
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./HA/config/:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  # port 6052
  # esphome:
  #   container_name: esphome
  #   image: esphome/esphome
  #   volumes:
  #     - ./ESPHome/config:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   privileged: true
  #   network_mode: host

  # port 3000
  nest-server:
    build: ./NestJs
    image: nest
    restart: unless-stopped
    network_mode: host

  # port 80
  svelte-server:
    build: ./Svelte
    image: svelte
    restart: unless-stopped
    network_mode: host

  # port 8080
  ustreamer:
    build: ./UStreamer
    image: ustreamer
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
