version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config/:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  nest-server:
    build: ./NestJs
    image: nest
    ports:
      - "3015:3000"

  svelte-server:
    build: ./Svelte
    image: svelte
    ports:
      - "3010:80"

  camera-server:
    build: ./Mjpg-streamer
    image: mjpg
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    ports:
      - "8080:8080"
